-- Run this in the Supabase SQL Editor.
-- It keeps public.supply as the item master, creates separate vendors and movements,
-- grants the GitHub Pages app access, and copies existing vendor names automatically.

create table if not exists public.supply_vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_person text,
  phone text,
  email text,
  tin text,
  address text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists supply_vendors_name_unique_idx
  on public.supply_vendors (lower(trim(name)));

create table if not exists public.supply_transactions (
  id bigint generated by default as identity primary key,
  supply_id bigint not null references public.supply(id) on update cascade on delete restrict,
  vendor_id bigint references public.supply_vendors(id) on update cascade on delete set null,
  direction text not null check (direction in ('IN', 'OUT')),
  quantity double precision not null check (quantity > 0),
  transaction_date date not null default current_date,
  reference_no text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists supply_transactions_supply_id_idx
  on public.supply_transactions (supply_id);
create index if not exists supply_transactions_date_idx
  on public.supply_transactions (transaction_date desc);
create index if not exists supply_transactions_direction_idx
  on public.supply_transactions (direction);

-- Copy distinct vendor names already stored in public.supply."Vendor".
insert into public.supply_vendors (name)
select distinct btrim(s."Vendor")
from public.supply s
where nullif(btrim(s."Vendor"), '') is not null
on conflict do nothing;

alter table public.supply enable row level security;
alter table public.supply_vendors enable row level security;
alter table public.supply_transactions enable row level security;

-- GitHub Pages uses the Supabase publishable/anon role.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.supply to anon, authenticated;
grant select, insert, update, delete on table public.supply_vendors to anon, authenticated;
grant select, insert, update, delete on table public.supply_transactions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Temporary public policies for this browser-only application.
drop policy if exists "public read supply" on public.supply;
create policy "public read supply" on public.supply for select to anon, authenticated using (true);
drop policy if exists "public write supply" on public.supply;
create policy "public write supply" on public.supply for all to anon, authenticated using (true) with check (true);

drop policy if exists "public read supply vendors" on public.supply_vendors;
create policy "public read supply vendors" on public.supply_vendors for select to anon, authenticated using (true);
drop policy if exists "public write supply vendors" on public.supply_vendors;
create policy "public write supply vendors" on public.supply_vendors for all to anon, authenticated using (true) with check (true);

drop policy if exists "public read supply transactions" on public.supply_transactions;
create policy "public read supply transactions" on public.supply_transactions for select to anon, authenticated using (true);
drop policy if exists "public write supply transactions" on public.supply_transactions;
create policy "public write supply transactions" on public.supply_transactions for all to anon, authenticated using (true) with check (true);

-- Show verification counts after the migration finishes.
select
  (select count(*) from public.supply) as supply_items,
  (select count(*) from public.supply_vendors) as vendors,
  (select count(*) from public.supply_transactions) as movements;
