-- Run this once in the Supabase SQL Editor.
-- It keeps public.supply as the item master and separates vendors and stock movements.

create table if not exists public.supply_vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_person text,
  phone text,
  email text,
  tin text,
  address text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supply_transactions (
  id bigint generated by default as identity primary key,
  supply_id bigint not null references public.supply(id) on update cascade on delete restrict,
  vendor_id bigint references public.supply_vendors(id) on update cascade on delete set null,
  direction text not null check (direction in ('IN', 'OUT')),
  quantity double precision not null check (quantity > 0),
  transaction_date date not null default current_date,
  reference_no text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists supply_transactions_supply_id_idx
  on public.supply_transactions (supply_id);
create index if not exists supply_transactions_date_idx
  on public.supply_transactions (transaction_date desc);
create index if not exists supply_transactions_direction_idx
  on public.supply_transactions (direction);

alter table public.supply_vendors enable row level security;
alter table public.supply_transactions enable row level security;

-- Temporary public policies for a GitHub Pages application using a publishable key.
-- Replace these with authenticated role policies when login/admin accounts are added.
drop policy if exists "public read supply vendors" on public.supply_vendors;
create policy "public read supply vendors" on public.supply_vendors for select using (true);
drop policy if exists "public write supply vendors" on public.supply_vendors;
create policy "public write supply vendors" on public.supply_vendors for all using (true) with check (true);

drop policy if exists "public read supply transactions" on public.supply_transactions;
create policy "public read supply transactions" on public.supply_transactions for select using (true);
drop policy if exists "public write supply transactions" on public.supply_transactions;
create policy "public write supply transactions" on public.supply_transactions for all using (true) with check (true);

-- The existing public.supply table also needs suitable RLS policies when RLS is enabled.
