const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'MVR'});const num=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});
const KEY='villimale-complete-system-v1';
const seed={products:[{id:1,name:'Rice 5 kg',category:'Grocery',unit:'bag',cost:85,price:105,stock:34},{id:2,name:'Cooking Oil 1 L',category:'Grocery',unit:'btl',cost:29,price:38,stock:47},{id:3,name:'Milk 1 L',category:'Dairy',unit:'pkt',cost:18,price:23,stock:25},{id:4,name:'Water 1.5 L',category:'Beverage',unit:'btl',cost:8,price:12,stock:72},{id:5,name:'Eggs 12 pcs',category:'Dairy',unit:'tray',cost:32,price:40,stock:18},{id:6,name:'Tuna 185 g',category:'Canned',unit:'tin',cost:16,price:22,stock:41}],vendors:[{id:1,name:'Lily Store',phone:'3332211',email:'orders@lily.mv'},{id:2,name:'Fantasy Store',phone:'3322712',email:''}],sales:[],purchases:[],stockOut:[],cart:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed);let page='dashboard';
const root=document.querySelector('#page-root');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);const id=rows=>Math.max(0,...rows.map(x=>Number(x.id)))+1;
const header=(title,desc,actions='')=>`<header class="page-head" data-area="Page Header"><div><h1>${title}</h1><p>${desc}</p></div><div class="actions" data-area="Actions">${actions}</div></header>`;
const kpi=(label,value,note)=>`<article class="card kpi" data-area="KPI Cards"><small>${label}</small><strong>${value}</strong><em>${note}</em></article>`;
const productOptions=()=>state.products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${num.format(p.stock)} ${esc(p.unit)}</option>`).join('');
const vendorOptions=()=>state.vendors.map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('');
function dashboard(){const revenue=state.sales.reduce((s,x)=>s+x.total,0),value=state.products.reduce((s,p)=>s+p.stock*p.cost,0),low=state.products.filter(p=>p.stock<=20).length;return header('Business Dashboard','Sales, inventory, purchasing and operational performance.')+`<section class="kpis" data-area="KPI Summary">${kpi('Today sales',money.format(revenue),'Recorded sales revenue')}${kpi('Stock value',money.format(value),'Current cost value')}${kpi('Products',num.format(state.products.length),'Active catalogue')}${kpi('Low stock',low,'Items at 20 or below')}</section><section class="grid two" data-area="Primary Content"><article class="card"><h2>Recent sales</h2>${salesTable(state.sales.slice(0,8))}</article><article class="card" data-area="Secondary Panel"><h2>Stock attention</h2>${stockTable(state.products.filter(p=>p.stock<=20))}</article></section>`}
function sales(){return header('Sales / POS','Select products, review stock, collect payment and create a receipt.','<button class="btn secondary" data-go="sales-history">Sales history</button>')+`<section class="grid two"><article class="card" data-area="Primary Content"><div class="toolbar" data-area="Filter / Toolbar"><input class="input" id="product-search" placeholder="Search products"></div><div class="products" id="product-grid">${productCards(state.products)}</div></article><aside class="card" data-area="Secondary Panel"><h2>Current sale</h2><div id="cart">${cartHtml()}</div></aside></section>`}
function productCards(rows){return rows.map(p=>`<button class="product" data-add-cart="${p.id}"><strong>${esc(p.name)}</strong><small>${esc(p.category)} · Stock ${num.format(p.stock)} ${esc(p.unit)}</small><div class="price">${money.format(p.price)}</div></button>`).join('')||'<div class="empty">No products found.</div>'}
function cartHtml(){if(!state.cart.length)return'<div class="empty">Select a product to start a sale.</div>';const total=state.cart.reduce((s,x)=>s+x.qty*x.price,0);return state.cart.map(x=>`<div class="cart-row"><div><strong>${esc(x.name)}</strong><br><small>${money.format(x.price)} each</small></div><input class="input" type="number" min="1" max="${x.stock}" value="${x.qty}" data-cart-qty="${x.id}"><button class="btn danger" data-cart-remove="${x.id}">×</button></div>`).join('')+`<div class="cart-total"><span>Total</span><span>${money.format(total)}</span></div><div class="field" style="margin-top:15px"><label>Payment method</label><select class="select" id="payment"><option>Cash</option><option>Card</option><option>Transfer</option><option>Credit</option></select></div><button class="btn primary" style="width:100%" data-checkout>Complete sale</button>`}
function salesHistory(){return header('Sales History','Receipts, payments and completed transactions.','<button class="btn primary" data-go="sales">New sale</button>')+`<article class="card" data-area="Data Table">${salesTable(state.sales)}</article>`}
function salesTable(rows){if(!rows.length)return'<div class="empty">No sales recorded.</div>';return`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Items</th><th>Payment</th><th>Total</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.receipt)}</strong></td><td>${esc(x.date)}</td><td>${x.items.reduce((s,i)=>s+i.qty,0)}</td><td>${esc(x.payment)}</td><td>${money.format(x.total)}</td></tr>`).join('')}</tbody></table></div>`}
function products(){return header('Products','Manage selling price, cost, categories and opening stock.','<button class="btn primary" data-open-product>Add product</button>')+`<section class="card" data-area="Data Table">${productTable()}</section><section id="product-form-wrap"></section>`}
function productTable(){return`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Unit</th><th>Cost</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td>${esc(p.unit)}</td><td>${money.format(p.cost)}</td><td>${money.format(p.price)}</td><td>${num.format(p.stock)}</td><td><span class="pill ${p.stock<=20?'warn':'good'}">${p.stock<=20?'Low':'Available'}</span></td></tr>`).join('')}</tbody></table></div>`}
function productForm(){return`<form class="card" id="product-form" style="margin-top:14px" data-area="Form / Fields"><h2>Add product</h2><div class="form-grid"><div class="field"><label>Name</label><input class="input" name="name" required></div><div class="field"><label>Category</label><input class="input" name="category" required></div><div class="field"><label>Unit</label><input class="input" name="unit" required></div><div class="field"><label>Cost</label><input class="input" name="cost" type="number" step=".01" required></div><div class="field"><label>Selling price</label><input class="input" name="price" type="number" step=".01" required></div><div class="field"><label>Opening stock</label><input class="input" name="stock" type="number" step=".01" required></div></div><button class="btn primary">Save product</button></form>`}
function inventory(){const value=state.products.reduce((s,p)=>s+p.stock*p.cost,0);return header('Inventory','Live quantities, valuation and low-stock control.')+`<section class="kpis" data-area="KPI Summary">${kpi('Stock value',money.format(value),'At current cost')}${kpi('Units in stock',num.format(state.products.reduce((s,p)=>s+p.stock,0)),'Across all products')}${kpi('Low stock',state.products.filter(p=>p.stock<=20).length,'Requires attention')}${kpi('Out of stock',state.products.filter(p=>p.stock<=0).length,'Unavailable items')}</section><article class="card" data-area="Data Table">${stockTable(state.products)}</article>`}
function stockTable(rows){if(!rows.length)return'<div class="empty">No items require attention.</div>';return`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Current stock</th><th>Cost value</th><th>Status</th></tr></thead><tbody>${rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td>${num.format(p.stock)} ${esc(p.unit)}</td><td>${money.format(p.stock*p.cost)}</td><td><span class="pill ${p.stock<=20?'warn':'good'}">${p.stock<=0?'Out':p.stock<=20?'Low':'Healthy'}</span></td></tr>`).join('')}</tbody></table></div>`}
function purchase(){return header('Supply In / Purchases','Receive products from vendors and increase available stock.')+movementForm('purchase')+`<article class="card" style="margin-top:14px" data-area="Data Table"><h2>Purchase history</h2>${movementTable(state.purchases,'Purchase')}</article>`}
function stockOut(){return header('Supply Out','Record damage, internal use, transfer or adjustment.')+movementForm('out')+`<article class="card" style="margin-top:14px" data-area="Data Table"><h2>Supply-out history</h2>${movementTable(state.stockOut,'Supply Out')}</article>`}
function movementForm(type){const incoming=type==='purchase';return`<form class="card" id="${type}-form" data-area="Form / Fields"><h2>${incoming?'Receive stock':'Issue stock'}</h2><div class="form-grid"><div class="field"><label>Product</label><select class="select" name="product" required><option value="">Select</option>${productOptions()}</select></div>${incoming?`<div class="field"><label>Vendor</label><select class="select" name="vendor"><option value="">Select</option>${vendorOptions()}</select></div>`:''}<div class="field"><label>Quantity</label><input class="input" name="qty" type="number" min=".01" step=".01" required></div><div class="field"><label>Date</label><input class="input" name="date" type="date" value="${today()}" required></div><div class="field"><label>${incoming?'Purchase cost':'Reason'}</label><input class="input" name="${incoming?'cost':'reason'}" ${incoming?'type="number" step=".01"':''} required></div><div class="field"><label>Reference</label><input class="input" name="reference"></div></div><div class="notice" data-stock-preview>Select a product to see current and resulting stock.</div><button class="btn primary">${incoming?'Save purchase':'Save supply out'}</button></form>`}
function movementTable(rows,label){if(!rows.length)return`<div class="empty">No ${label.toLowerCase()} records.</div>`;return`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Quantity</th><th>Reference</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.productName)}</td><td>${num.format(x.qty)}</td><td>${esc(x.reference||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function vendors(){return header('Vendors','Supplier contacts and purchasing relationships.')+`<section class="grid two"><form class="card" id="vendor-form" data-area="Form / Fields"><h2>Add vendor</h2><div class="field"><label>Name</label><input class="input" name="name" required></div><div class="field"><label>Phone</label><input class="input" name="phone"></div><div class="field"><label>Email</label><input class="input" name="email" type="email"></div><button class="btn primary">Save vendor</button></form><article class="card" data-area="Data Table"><h2>Vendor directory</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th></tr></thead><tbody>${state.vendors.map(v=>`<tr><td><strong>${esc(v.name)}</strong></td><td>${esc(v.phone||'—')}</td><td>${esc(v.email||'—')}</td></tr>`).join('')}</tbody></table></div></article></section>`}
function reports(){const revenue=state.sales.reduce((s,x)=>s+x.total,0),cost=state.sales.reduce((s,x)=>s+x.items.reduce((a,i)=>a+i.cost*i.qty,0),0);return header('Reports','Sales, purchasing, margin and stock summaries.')+`<section class="kpis" data-area="KPI Summary">${kpi('Revenue',money.format(revenue),'All recorded sales')}${kpi('Estimated margin',money.format(revenue-cost),'Revenue minus item cost')}${kpi('Purchases',state.purchases.length,'Receiving transactions')}${kpi('Sales receipts',state.sales.length,'Completed checkouts')}</section><section class="grid two"><article class="card"><h2>Sales report</h2>${salesTable(state.sales)}</article><article class="card"><h2>Inventory report</h2>${stockTable(state.products)}</article></section>`}
function admin(){return header('Admin & Settings','System controls, data state, themes and maintenance.')+`<section class="grid two"><article class="card"><h2>System modules</h2><p>Sales, products, inventory, purchasing, supply out, vendors, reports and themes are active.</p><div class="notice">Temporary local data is enabled. Supabase remains disconnected until the new structure is approved.</div></article><article class="card"><h2>Data tools</h2><p>Reset the temporary system to the original demonstration records.</p><button class="btn danger" data-reset>Reset demonstration data</button></article></section>`}
const pages={dashboard,sales,'sales-history':salesHistory,products,inventory,purchase,'stock-out':stockOut,vendors,reports,admin};
function render(next=page){page=pages[next]?next:'dashboard';root.innerHTML=pages[page]();document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));location.hash=page;document.body.classList.remove('menu-open');installHelper()}
function installHelper(){document.querySelector('.helper')?.remove();const areas=[...new Set([...document.querySelectorAll('[data-area]')].map(x=>x.dataset.area))];const el=document.createElement('div');el.className='helper';el.innerHTML=`<button class="helper-toggle">Page helper</button><div class="helper-panel hidden">${areas.map(a=>`<button data-find="${a}">${a}</button>`).join('')}</div>`;document.body.append(el)}
function checkout(){if(!state.cart.length)return;for(const c of state.cart){const p=state.products.find(x=>x.id===c.id);if(!p||c.qty>p.stock)return alert(`Not enough stock for ${c.name}`)}const items=state.cart.map(c=>{const p=state.products.find(x=>x.id===c.id);p.stock-=c.qty;return{...c,cost:p.cost}});const total=items.reduce((s,x)=>s+x.qty*x.price,0);state.sales.unshift({id:id(state.sales),receipt:`S-${String(id(state.sales)).padStart(5,'0')}`,date:today(),payment:document.querySelector('#payment')?.value||'Cash',items,total});state.cart=[];save();render('sales-history')}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go],[data-page]');if(go)return render(go.dataset.go||go.dataset.page);if(e.target.closest('[data-menu]'))return document.body.classList.toggle('menu-open');const add=e.target.closest('[data-add-cart]');if(add){const p=state.products.find(x=>x.id===Number(add.dataset.addCart));const c=state.cart.find(x=>x.id===p.id);if(c)c.qty=Math.min(p.stock,c.qty+1);else state.cart.push({id:p.id,name:p.name,price:p.price,stock:p.stock,qty:1});save();return render('sales')}const remove=e.target.closest('[data-cart-remove]');if(remove){state.cart=state.cart.filter(x=>x.id!==Number(remove.dataset.cartRemove));save();return render('sales')}if(e.target.closest('[data-checkout]'))return checkout();if(e.target.closest('[data-open-product]')){document.querySelector('#product-form-wrap').innerHTML=productForm();return}if(e.target.closest('[data-reset]')){if(confirm('Reset all demonstration data?')){state=structuredClone(seed);save();render('dashboard')}return}if(e.target.closest('.helper-toggle'))return document.querySelector('.helper-panel').classList.toggle('hidden');const find=e.target.closest('[data-find]');if(find){document.querySelectorAll('.highlight').forEach(x=>x.classList.remove('highlight'));const target=document.querySelector(`[data-area="${find.dataset.find}"]`);target?.classList.add('highlight');target?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>target?.classList.remove('highlight'),1800)}});
document.addEventListener('input',e=>{if(e.target.id==='product-search')document.querySelector('#product-grid').innerHTML=productCards(state.products.filter(p=>p.name.toLowerCase().includes(e.target.value.toLowerCase())));if(e.target.matches('[data-cart-qty]')){const c=state.cart.find(x=>x.id===Number(e.target.dataset.cartQty));c.qty=Math.max(1,Math.min(c.stock,Number(e.target.value)||1));save();document.querySelector('#cart').innerHTML=cartHtml()}if(e.target.closest('#purchase-form,#out-form')&&['product','qty'].includes(e.target.name)){const f=e.target.form,p=state.products.find(x=>x.id===Number(f.product.value)),q=Number(f.qty.value)||0;if(p){const after=f.id==='purchase-form'?p.stock+q:p.stock-q;f.querySelector('[data-stock-preview]').textContent=`Current stock: ${num.format(p.stock)} ${p.unit} · Stock after: ${num.format(after)} ${p.unit}`}}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(f.id==='product-form'){state.products.push({id:id(state.products),name:d.name,category:d.category,unit:d.unit,cost:Number(d.cost),price:Number(d.price),stock:Number(d.stock)});save();return render('products')}if(f.id==='vendor-form'){state.vendors.push({id:id(state.vendors),name:d.name,phone:d.phone,email:d.email});save();return render('vendors')}if(f.id==='purchase-form'||f.id==='out-form'){const p=state.products.find(x=>x.id===Number(d.product)),q=Number(d.qty);if(!p)return;if(f.id==='out-form'&&q>p.stock)return alert(`Only ${p.stock} ${p.unit} available`);if(f.id==='purchase-form'){p.stock+=q;if(Number(d.cost)>0)p.cost=Number(d.cost);state.purchases.unshift({id:id(state.purchases),productId:p.id,productName:p.name,qty:q,date:d.date,reference:d.reference,vendor:Number(d.vendor)})}else{p.stock-=q;state.stockOut.unshift({id:id(state.stockOut),productId:p.id,productName:p.name,qty:q,date:d.date,reference:d.reference,reason:d.reason})}save();return render(f.id==='purchase-form'?'purchase':'stock-out')}});
document.querySelector('#theme').addEventListener('change',e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('complete-theme',e.target.value)});document.documentElement.dataset.theme=localStorage.getItem('complete-theme')||'light';document.querySelector('#theme').value=document.documentElement.dataset.theme;window.addEventListener('hashchange',()=>render(location.hash.slice(1)));render(location.hash.slice(1)||'dashboard');