const definitions={
 sell:['Point of Sale','Sell','Create and complete customer sales.','New Sale',['Open Carts','Today’s Sales','Items Sold']],
 register:['Point of Sale','Register','Open, close and monitor the active cash register.','Open Register',['Register Balance','Cash Sales','Card Sales']],
 'register-sessions':['Point of Sale','Register Sessions','Review register openings, closings and cash movements.','New Session',['Open Sessions','Closed Today','Variance']],
 quotations:['Point of Sale','Quotations','Prepare and manage customer quotations.','New Quotation',['Draft','Approved','Converted']],
 'online-payments':['Point of Sale','Online Payments','Track payment links and online transactions.','Payment Link',['Received','Pending','Failed']],
 'bill-history':['Point of Sale','Bill History','Find receipts, invoices, returns and completed sales.','New Sale',['Today','This Month','Refunded']],
 customers:['Customers','Customers','Manage customer profiles, balances and loyalty activity.','New Customer',['Total Customers','New This Month','With Balance']],
 products:['Products','Products','Manage products, prices, categories and availability.','New Product',['Active Products','Low Stock','Categories']],
 inventory:['Inventory','Inventory','Track stock levels, adjustments and movements.','Stock Adjustment',['Stock Value','Low Stock','Out of Stock']],
 ecommerce:['Ecommerce','Ecommerce','Manage online orders, storefront items and fulfilment.','New Order',['Online Orders','Awaiting Pickup','Completed']],
 supply:['Supply','Supply','Manage suppliers, purchases and received inventory.','New Purchase',['Suppliers','Open Purchases','Received']],
 reports:['Reports','Reports','Open sales, inventory, customer and financial reports.','Create Report',['Saved Reports','Scheduled','Generated Today']],
 billing:['Admin','Billing','Manage subscription, invoices and payment details.','Update Billing',['Current Plan','Next Invoice','Payment Methods']],
 settings:['Admin','Settings','Configure company, receipt, currency and operational preferences.','Save Settings',['Configured','Required','Optional']],
 users:['Admin','Users','Manage login access, roles and account status.','New User',['Active Users','Administrators','Invited']],
 employees:['Admin','Employees','Manage employee profiles, assignments and attendance access.','New Employee',['Employees','Active','On Leave']],
 locations:['Admin','Locations','Manage outlets, registers and stock locations.','New Location',['Locations','Registers','Warehouses']],
 taxes:['Admin','Taxes','Configure GST and other tax rules used by sales.','New Tax',['Tax Rules','Active','Exemptions']],
 'loyalty-programs':['Admin','Loyalty Programs','Configure points, rewards and customer eligibility.','New Program',['Programs','Members','Rewards Issued']],
 'print-templates':['Admin','Print Templates','Customize receipts, invoices, quotations and labels.','New Template',['Templates','Active','Draft']],
 integrations:['Admin','Integrations','Connect Ewity with payments, ecommerce and business services.','Add Integration',['Connected','Available','Needs Attention']],
 notification:['Admin','Notification','Configure operational alerts and customer notifications.','New Rule',['Active Rules','Sent Today','Failed']],
 'audit-logs':['Admin','Audit Logs','Review important user and system activity.','Export Logs',['Events Today','Users Active','Security Events']],
 help:['Support','Help','Find guides, training videos and assistance for Ewity POS.','Contact Support',['Guides','Videos','Open Tickets']]
};
const rowsByRoute={};
const sampleNames=['Main Store','Standard Record','Daily Operation','Customer Request','System Configuration','Staff Activity','Online Transaction','Inventory Update'];
export function getModuleTitle(route){return definitions[route]?.[1]||'Ewity POS'}
export function initModulePage(route){const d=definitions[route];if(!d)return;const[group,title,description,action,metrics]=d;document.querySelector('#module-group').textContent=group;document.querySelector('#module-heading').textContent=title;document.querySelector('#module-description').textContent=description;document.querySelector('#module-primary').textContent=`＋ ${action}`;const summary=document.querySelector('#module-summary');summary.innerHTML=metrics.map((label,i)=>`<article class="module-stat"><small>${label}</small><strong>${[24,8,3][i]}</strong><span>${i===1?'This month':'Current'}</span></article>`).join('');let rows=rowsByRoute[route]||(rowsByRoute[route]=sampleNames.slice(0,6).map((name,i)=>({id:i+1,name:`${title} ${name}`,description:`${group} record ${String(i+1).padStart(2,'0')}`,status:i===2?'Pending':'Active'})));const search=document.querySelector('#module-search'),body=document.querySelector('#module-table-body'),modal=document.querySelector('#module-modal'),form=document.querySelector('#module-form');document.querySelector('#module-table-head').innerHTML='<tr><th>Name</th><th>Description</th><th>Status</th><th>Updated</th><th>Actions</th></tr>';function render(){const q=search.value.toLowerCase(),filtered=rows.filter(x=>!q||`${x.name} ${x.description} ${x.status}`.toLowerCase().includes(q));body.innerHTML=filtered.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.description}</td><td><span class="status-tag ${x.status.toLowerCase()}">${x.status}</span></td><td>Today</td><td class="row-actions"><button data-module-edit="${x.id}">✎</button><button data-module-delete="${x.id}">♲</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-row">No matching records.</td></tr>';document.querySelector('#module-result-count').textContent=`Showing ${filtered.length} records`}search.oninput=render;document.querySelector('#module-filter').onclick=()=>{search.focus()};document.querySelector('#module-primary').onclick=()=>{form.reset();modal.hidden=false};document.querySelectorAll('[data-module-close]').forEach(x=>x.onclick=()=>modal.hidden=true);body.onclick=e=>{const edit=e.target.closest('[data-module-edit]'),remove=e.target.closest('[data-module-delete]');if(edit){const item=rows.find(x=>x.id===+edit.dataset.moduleEdit);form.name.value=item.name;form.description.value=item.description;form.status.value=item.status;form.dataset.edit=item.id;modal.hidden=false}if(remove&&confirm('Delete this record?')){rows=rows.filter(x=>x.id!==+remove.dataset.moduleDelete);rowsByRoute[route]=rows;render()}};form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form)),id=+form.dataset.edit;if(id)rows=rows.map(x=>x.id===id?{...x,...data}:x);else rows.unshift({id:Date.now(),...data});rowsByRoute[route]=rows;delete form.dataset.edit;modal.hidden=true;render()};document.querySelector('#module-more').onclick=()=>alert(`All ${title} records are already shown in this prototype.`);render()}
export const moduleRoutes=Object.keys(definitions);
