pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={bytes:null,pdf:null,name:"",scale:1.25,selected:null,changes:[]};
const els={welcome:$("#welcome"),editor:$("#editor"),input:$("#fileInput"),drop:$("#dropZone"),pages:$("#pages"),thumbs:$("#thumbnails"),download:$("#downloadBtn"),undo:$("#undoBtn"),newBtn:$("#newBtn"),panel:$(".changes-panel"),empty:$("#emptyState"),form:$("#editForm"),replacement:$("#replacementText")};
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
["dragenter","dragover"].forEach(e=>els.drop.addEventListener(e,x=>{x.preventDefault();els.drop.classList.add("drag")}));
["dragleave","drop"].forEach(e=>els.drop.addEventListener(e,x=>{x.preventDefault();els.drop.classList.remove("drag")}));
els.drop.addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));
els.input.addEventListener("change",e=>loadFile(e.target.files[0]));
async function loadFile(file){if(!file||file.type!=="application/pdf"){toast("Please choose a PDF file");return}state.name=file.name;state.bytes=new Uint8Array(await file.arrayBuffer());try{state.pdf=await pdfjsLib.getDocument({data:state.bytes.slice()}).promise}catch(e){toast("This PDF could not be opened");return}
els.welcome.hidden=true;els.editor.hidden=false;els.newBtn.hidden=false;$("#fileName").textContent=file.name;$("#fileMeta").textContent=(file.size/1048576).toFixed(2)+" MB";$("#pageCount").textContent=state.pdf.numPages;state.changes=[];await renderAll();els.download.disabled=false;toast("PDF ready — click any text to edit")}
async function renderAll(){els.pages.innerHTML="";els.thumbs.innerHTML="";for(let n=1;n<=state.pdf.numPages;n++){await renderPage(n)}updateHistory()}
async function renderPage(n){const page=await state.pdf.getPage(n),vp=page.getViewport({scale:state.scale});const wrap=document.createElement("div");wrap.className="pdf-page";wrap.dataset.page=n;wrap.style.width=vp.width+"px";wrap.style.height=vp.height+"px";const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=vp.width;canvas.height=vp.height;wrap.append(canvas);els.pages.append(wrap);await page.render({canvasContext:ctx,viewport:vp}).promise;const content=await page.getTextContent();content.items.forEach((it,i)=>{if(!it.str.trim())return;const tx=pdfjsLib.Util.transform(vp.transform,it.transform),font=Math.max(6,Math.hypot(tx[2],tx[3])),h=Math.max(font,it.height*state.scale),w=Math.max(5,it.width*state.scale);const b=document.createElement("button");b.className="text-hit";b.dataset.index=i;b.style.left=tx[4]+"px";b.style.top=(tx[5]-h)+"px";b.style.width=w+"px";b.style.height=(h+3)+"px";b.title=it.str;b.setAttribute("aria-label","Edit "+it.str);b.addEventListener("click",()=>selectText({page:n,index:i,text:it.str,x:tx[4],y:tx[5]-h,w,h:h+3,font,button:b}));wrap.append(b)});
const tv=page.getViewport({scale:.2}),tc=document.createElement("canvas");tc.width=tv.width;tc.height=tv.height;await page.render({canvasContext:tc.getContext("2d"),viewport:tv}).promise;const th=document.createElement("div");th.className="thumb"+(n===1?" active":"");th.append(tc);const cap=document.createElement("span");cap.textContent="Page "+n;th.append(cap);th.onclick=()=>{wrap.scrollIntoView({behavior:"smooth"});$$(".thumb").forEach(x=>x.classList.remove("active"));th.classList.add("active")};els.thumbs.append(th)}
function selectText(sel){$$(".text-hit").forEach(x=>x.classList.remove("selected"));sel.button.classList.add("selected");state.selected=sel;els.empty.hidden=true;els.form.hidden=false;els.panel.classList.add("open");$("#panelTitle").textContent="Edit text";$("#originalText").textContent=sel.text;els.replacement.value=sel.text;$("#diffOld").textContent="− "+sel.text;$("#diffNew").textContent="+ "+sel.text;fitCheck();els.replacement.focus();els.replacement.select()}
els.replacement.addEventListener("input",()=>{$("#diffNew").textContent="+ "+els.replacement.value;fitCheck()});
function fitCheck(){if(!state.selected)return;const approx=els.replacement.value.length/Math.max(1,state.selected.text.length);const n=$("#fitNotice");n.textContent=approx>1.18?"May overflow — text will be reduced on export":"Fits inside the original area";n.classList.toggle("warn",approx>1.18)}
$("#applyBtn").onclick=()=>{if(!state.selected)return;const value=els.replacement.value.trim();if(!value){toast("Replacement cannot be empty");return}const s=state.selected;const change={...s,newText:value,id:Date.now()};delete change.button;state.changes.push(change);paintChange(change);closeEdit();updateHistory();toast("Change applied")};
function paintChange(c){const wrap=$('.pdf-page[data-page="'+c.page+'"]');const old=wrap.querySelector('.replacement-overlay[data-index="'+c.index+'"]');if(old)old.remove();const o=document.createElement("div");o.className="replacement-overlay";o.dataset.index=c.index;o.style.left=c.x+"px";o.style.top=c.y+"px";o.style.width=c.w+"px";o.style.height=c.h+"px";o.style.fontSize=Math.min(c.font,c.w/Math.max(1,c.newText.length)*1.65)+"px";o.textContent=c.newText;wrap.append(o)}
function closeEdit(){if(state.selected?.button)state.selected.button.classList.remove("selected");state.selected=null;els.form.hidden=true;els.empty.hidden=false;$("#panelTitle").textContent="No text selected";els.panel.classList.remove("open")}
$("#cancelBtn").onclick=closeEdit;$("#closePanel").onclick=closeEdit;
function updateHistory(){$("#changeCount").textContent=state.changes.length;els.undo.disabled=!state.changes.length;const list=$("#changeList");if(!state.changes.length){list.innerHTML='<p class="muted">Accepted changes will appear here.</p>';return}list.innerHTML="";state.changes.slice().reverse().forEach(c=>{const d=document.createElement("div");d.className="change-item";d.innerHTML="<small>Page "+c.page+"</small><b></b><span></span>";d.querySelector("b").textContent=c.text;d.querySelector("span").textContent=c.newText;list.append(d)})}
els.undo.onclick=()=>{const c=state.changes.pop();if(!c)return;const o=$('.pdf-page[data-page="'+c.page+'"] .replacement-overlay[data-index="'+c.index+'"]');if(o)o.remove();const prior=[...state.changes].reverse().find(x=>x.page===c.page&&x.index===c.index);if(prior)paintChange(prior);updateHistory();toast("Last change undone")};
els.newBtn.onclick=()=>location.reload();
$("#zoomIn").onclick=()=>zoom(.15);$("#zoomOut").onclick=()=>zoom(-.15);
async function zoom(d){state.scale=Math.min(2,Math.max(.65,state.scale+d));$("#zoomLabel").textContent=Math.round(state.scale/1.25*100)+"%";await renderAll();state.changes.forEach(paintChange)}
els.download.onclick=async()=>{if(!state.bytes)return;els.download.disabled=true;els.download.textContent="Preparing…";try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice()),font=await doc.embedFont(PDFLib.StandardFonts.Helvetica);for(const c of state.changes){const p=doc.getPage(c.page-1),sx=p.getWidth()/($('.pdf-page[data-page="'+c.page+'"]').clientWidth),sy=p.getHeight()/($('.pdf-page[data-page="'+c.page+'"]').clientHeight),x=c.x*sx,y=p.getHeight()-(c.y+c.h)*sy,w=c.w*sx,h=c.h*sy;let size=Math.max(5,c.font*sy*.82);while(font.widthOfTextAtSize(c.newText,size)>w&&size>5)size-=.5;p.drawRectangle({x:x-1,y:y-1,width:w+2,height:h+2,color:PDFLib.rgb(1,1,1)});p.drawText(c.newText,{x,y:y+Math.max(1,(h-size)*.45),size,font,color:PDFLib.rgb(.05,.05,.06),maxWidth:w})}const out=await doc.save(),blob=new Blob([out],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,"")+"-edited.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Edited PDF downloaded")}catch(e){console.error(e);toast("Could not export this PDF")}finally{els.download.disabled=false;els.download.textContent="Download PDF"}};
