pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={bytes:null,pdf:null,name:"",scale:1.25,selected:null,changes:[],ocr:{},currentPage:1,selectedPages:new Set([1])};
const els={welcome:$("#welcome"),editor:$("#editor"),input:$("#fileInput"),drop:$("#dropZone"),pages:$("#pages"),thumbs:$("#thumbnails"),download:$("#downloadBtn"),undo:$("#undoBtn"),newBtn:$("#newBtn"),wordBtn:$("#wordModeBtn"),panel:$(".changes-panel"),empty:$("#emptyState"),form:$("#editForm"),replacement:$("#replacementText")};
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
["dragenter","dragover"].forEach(e=>els.drop.addEventListener(e,x=>{x.preventDefault();els.drop.classList.add("drag")}));
["dragleave","drop"].forEach(e=>els.drop.addEventListener(e,x=>{x.preventDefault();els.drop.classList.remove("drag")}));
els.drop.addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));
els.input.addEventListener("change",e=>loadFile(e.target.files[0]));
async function loadFile(file){if(!file||file.type!=="application/pdf"){toast("Please choose a PDF file");return}state.name=file.name;state.bytes=new Uint8Array(await file.arrayBuffer());try{state.pdf=await pdfjsLib.getDocument({data:state.bytes.slice()}).promise}catch(e){toast("This PDF could not be opened");return}
els.welcome.hidden=true;els.editor.hidden=false;els.newBtn.hidden=false;els.wordBtn.hidden=false;$("#fileName").textContent=file.name;$("#fileMeta").textContent=(file.size/1048576).toFixed(2)+" MB";$("#pageCount").textContent=state.pdf.numPages;state.changes=[];state.ocr={};state.currentPage=1;state.selectedPages=new Set([1]);await renderAll();els.download.disabled=false;toast("PDF ready — click any text to edit")}
async function renderAll(){els.pages.innerHTML="";els.thumbs.innerHTML="";for(let n=1;n<=state.pdf.numPages;n++){await renderPage(n)}updateHistory()}
async function renderPage(n){const page=await state.pdf.getPage(n),vp=page.getViewport({scale:state.scale});const wrap=document.createElement("div");wrap.className="pdf-page";wrap.dataset.page=n;wrap.style.width=vp.width+"px";wrap.style.height=vp.height+"px";const canvas=document.createElement("canvas"),ctx=canvas.getContext("2d"),outputScale=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(vp.width*outputScale);canvas.height=Math.floor(vp.height*outputScale);canvas.style.width=vp.width+"px";canvas.style.height=vp.height+"px";wrap.append(canvas);els.pages.append(wrap);await page.render({canvasContext:ctx,viewport:vp,transform:outputScale===1?null:[outputScale,0,0,outputScale,0,0]}).promise;const content=await page.getTextContent();const nativeItems=content.items.filter(it=>it.str&&it.str.trim());
const addHit=(spec)=>{const b=document.createElement("button");b.className="text-hit"+(String(spec.index).startsWith("ocr-")?" ocr-hit":"");b.dataset.index=spec.index;b.textContent=spec.text;b.style.fontSize=Math.max(6,spec.font||10)+"px";b.style.left=spec.x+"px";b.style.top=spec.y+"px";b.style.width=Math.max(5,spec.w)+"px";b.style.height=Math.max(7,spec.h)+"px";b.title=spec.text;b.setAttribute("aria-label","Edit "+spec.text);b.addEventListener("click",()=>selectText({...spec,page:n,button:b}));wrap.append(b)};
nativeItems.forEach((it,i)=>{const tx=pdfjsLib.Util.transform(vp.transform,it.transform),font=Math.max(6,Math.hypot(tx[2],tx[3])),h=Math.max(font,it.height*state.scale),w=Math.max(5,it.width*state.scale);addHit({index:i,text:it.str,x:tx[4],y:tx[5]-h,w,h:h+3,font})});
if(nativeItems.length<3&&window.Tesseract){let words=state.ocr[n];if(!words){$("#statusText").textContent="Scanning page "+n+" for editable text…";try{const result=await Tesseract.recognize(canvas,"eng",{logger:m=>{if(m.status==="recognizing text")$("#statusText").textContent="Scanning page "+n+" — "+Math.round((m.progress||0)*100)+"%"}});words=(result.data.words||[]).filter(w=>w.text&&w.text.trim()&&w.confidence>35).map((w,i)=>({index:"ocr-"+i,text:w.text.trim(),nx:w.bbox.x0/canvas.width,ny:w.bbox.y0/canvas.height,nw:(w.bbox.x1-w.bbox.x0)/canvas.width,nh:(w.bbox.y1-w.bbox.y0)/canvas.height}));state.ocr[n]=words}catch(e){console.error("OCR failed",e);words=[]}}words.forEach(w=>addHit({index:w.index,text:w.text,x:w.nx*vp.width,y:w.ny*vp.height,w:w.nw*vp.width,h:w.nh*vp.height,font:Math.max(7,w.nh*vp.height*.82)}));$("#statusText").textContent=words.length?"OCR ready — click any outlined word to edit":"No editable text detected on page "+n}
const tv=page.getViewport({scale:.32}),tc=document.createElement("canvas"),thumbScale=Math.min(window.devicePixelRatio||1,1.5);tc.width=Math.floor(tv.width*thumbScale);tc.height=Math.floor(tv.height*thumbScale);tc.style.width=tv.width+"px";tc.style.height=tv.height+"px";await page.render({canvasContext:tc.getContext("2d"),viewport:tv,transform:thumbScale===1?null:[thumbScale,0,0,thumbScale,0,0]}).promise;const th=document.createElement("div");th.className="thumb"+(n===1?" active selected-page":"");th.append(tc);const cap=document.createElement("span");cap.textContent="Page "+n;th.append(cap);th.dataset.page=n;th.draggable=true;const pick=document.createElement("label"),check=document.createElement("input"),pickText=document.createElement("span");pick.className="thumb-select";check.type="checkbox";check.checked=state.selectedPages.has(n);check.setAttribute("aria-label","Select page "+n);pickText.textContent="Select";pick.append(check,pickText);th.append(pick);check.onclick=e=>e.stopPropagation();check.onchange=()=>{check.checked?state.selectedPages.add(n):state.selectedPages.delete(n);th.classList.toggle("selected-page",check.checked)};th.onclick=()=>{state.currentPage=n;wrap.scrollIntoView({behavior:"smooth"});$(".thumb").forEach(x=>x.classList.remove("active"));th.classList.add("active")};th.addEventListener("dragstart",e=>{th.classList.add("dragging");e.dataTransfer.setData("text/plain",String(n));e.dataTransfer.effectAllowed="move"});th.addEventListener("dragend",()=>th.classList.remove("dragging"));th.addEventListener("dragover",e=>{e.preventDefault();th.classList.add("drag-over")});th.addEventListener("dragleave",()=>th.classList.remove("drag-over"));th.addEventListener("drop",async e=>{e.preventDefault();th.classList.remove("drag-over");const from=Number(e.dataTransfer.getData("text/plain"));if(from&&from!==n)await reorderPdfPage(from,n)});els.thumbs.append(th)}
function selectText(sel){$$(".text-hit").forEach(x=>x.classList.remove("selected"));sel.button.classList.add("selected");state.selected=sel;els.empty.hidden=true;els.form.hidden=false;els.panel.classList.add("open");$("#panelTitle").textContent="Edit text";$("#originalText").textContent=sel.text;els.replacement.value=sel.text;$("#diffOld").textContent="− "+sel.text;$("#diffNew").textContent="+ "+sel.text;fitCheck();els.replacement.focus();els.replacement.select()}
els.replacement.addEventListener("input",()=>{$("#diffNew").textContent="+ "+els.replacement.value;fitCheck()});
function fitCheck(){if(!state.selected)return;const approx=els.replacement.value.length/Math.max(1,state.selected.text.length);const n=$("#fitNotice");n.textContent=approx>1.18?"May overflow — text will be reduced on export":"Fits inside the original area";n.classList.toggle("warn",approx>1.18)}
$("#applyBtn").onclick=()=>{if(!state.selected)return;const value=els.replacement.value.trim();if(!value){toast("Replacement cannot be empty");return}const s=state.selected;const change={...s,newText:value,id:Date.now()};delete change.button;state.changes.push(change);paintChange(change);closeEdit();updateHistory();toast("Change applied")};
function paintChange(c){const wrap=$('.pdf-page[data-page="'+c.page+'"]');const old=wrap.querySelector('.replacement-overlay[data-index="'+c.index+'"]');if(old)old.remove();const o=document.createElement("div");o.className="replacement-overlay";o.dataset.index=c.index;o.style.left=c.x+"px";o.style.top=c.y+"px";o.style.width=c.w+"px";o.style.height=c.h+"px";o.style.fontSize=Math.min(c.font,c.w/Math.max(1,c.newText.length)*1.65)+"px";o.textContent=c.newText;wrap.append(o)}
function closeEdit(){if(state.selected?.button)state.selected.button.classList.remove("selected");state.selected=null;els.form.hidden=true;els.empty.hidden=false;$("#panelTitle").textContent="No text selected";els.panel.classList.remove("open")}
$("#cancelBtn").onclick=closeEdit;$("#closePanel").onclick=closeEdit;
function updateHistory(){$("#changeCount").textContent=state.changes.length;els.undo.disabled=!state.changes.length;const list=$("#changeList");if(!state.changes.length){list.innerHTML='<p class="muted">Accepted changes will appear here.</p>';return}list.innerHTML="";state.changes.slice().reverse().forEach(c=>{const d=document.createElement("div");d.className="change-item";d.innerHTML="<small>Page "+c.page+"</small><b></b><span></span>";d.querySelector("b").textContent=c.text;d.querySelector("span").textContent=c.newText;list.append(d)})}
els.undo.onclick=()=>{const c=state.changes.pop();if(!c)return;const o=$('.pdf-page[data-page="'+c.page+'"] .replacement-overlay[data-index="'+c.index+'"]');if(o)o.remove();const prior=[...state.changes].reverse().find(x=>x.page===c.page&&x.index===c.index);if(prior)paintChange(prior);updateHistory();toast("Last change undone")};
els.newBtn.onclick=()=>location.reload();
$("#zoomIn").onclick=()=>zoom(.15);$("#zoomOut").onclick=()=>zoom(-.15);
async function zoom(d){state.scale=Math.min(2,Math.max(.65,state.scale+d));$("#zoomLabel").textContent=Math.round(state.scale/1.25*100)+"%";await renderAll();state.changes.forEach(paintChange)}
els.download.onclick=async()=>{if(!state.bytes)return;els.download.disabled=true;els.download.textContent="Preparing…";try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice()),font=await doc.embedFont(PDFLib.StandardFonts.Helvetica);for(const c of state.changes){const p=doc.getPage(c.page-1),sx=p.getWidth()/($('.pdf-page[data-page="'+c.page+'"]').clientWidth),sy=p.getHeight()/($('.pdf-page[data-page="'+c.page+'"]').clientHeight),x=c.x*sx,y=p.getHeight()-(c.y+c.h)*sy,w=c.w*sx,h=c.h*sy;let size=Math.max(5,c.font*sy*.82);while(font.widthOfTextAtSize(c.newText,size)>w&&size>5)size-=.5;p.drawRectangle({x:x-1,y:y-1,width:w+2,height:h+2,color:PDFLib.rgb(1,1,1)});p.drawText(c.newText,{x,y:y+Math.max(1,(h-size)*.45),size,font,color:PDFLib.rgb(.05,.05,.06),maxWidth:w})}const out=await doc.save(),blob=new Blob([out],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,"")+"-edited.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Edited PDF downloaded")}catch(e){console.error(e);toast("Could not export this PDF")}finally{els.download.disabled=false;els.download.textContent="Download PDF"}};

let documentModel=[],activeBlockId=null;
els.wordBtn.addEventListener("click",openWordMode);
$("#backToPdf").addEventListener("click",()=>{$("#wordEditor").hidden=true;els.editor.hidden=false;els.wordBtn.textContent="Word Mode"});
async function openWordMode(){els.editor.hidden=true;$("#wordEditor").hidden=false;els.wordBtn.textContent="Word Mode";$("#wordDocument").innerHTML='<p class="muted">Building editable document…</p>';documentModel=await buildDocumentModel();renderWordDocument();await renderOriginalReference();toast("Word workspace ready")}
async function buildDocumentModel(){const blocks=[];for(let pageNo=1;pageNo<=state.pdf.numPages;pageNo++){const page=await state.pdf.getPage(pageNo),content=await page.getTextContent(),items=content.items.filter(x=>x.str&&x.str.trim());let lines=[];
if(items.length>=3){const sorted=items.map(x=>{const size=Math.max(8,Math.abs(x.transform[3])||10);return {text:x.str.trim(),x:x.transform[4],y:x.transform[5],size,width:x.width||x.str.length*size*.5,height:x.height||size,fontFamily:content.styles?.[x.fontName]?.fontFamily||x.fontName||"auto"}}).sort((a,b)=>Math.abs(b.y-a.y)>4?b.y-a.y:a.x-b.x);for(const item of sorted){let line=lines.find(l=>Math.abs(l.y-item.y)<4);if(!line){line={y:item.y,items:[],size:item.size};lines.push(line)}line.items.push(item);line.size=Math.max(line.size,item.size)}lines=lines.sort((a,b)=>b.y-a.y).map(l=>{const ordered=l.items.sort((a,b)=>a.x-b.x),minX=Math.min(...ordered.map(x=>x.x)),maxX=Math.max(...ordered.map(x=>x.x+x.width));return {text:ordered.map(x=>x.text).join(" "),size:l.size,bounds:{unit:"pdf",x:minX,y:l.y-l.size*.25,w:Math.max(10,maxX-minX),h:l.size*1.25},fontFamily:ordered[0]?.fontFamily||"auto"}})}
else{const words=state.ocr[pageNo]||[];const rows=[];words.slice().sort((a,b)=>Math.abs(a.ny-b.ny)>.012?a.ny-b.ny:a.nx-b.nx).forEach(w=>{let row=rows.find(r=>Math.abs(r.y-w.ny)<.012);if(!row){row={y:w.ny,words:[]};rows.push(row)}row.words.push(w)});lines=rows.sort((a,b)=>a.y-b.y).map(r=>{const ordered=r.words.sort((a,b)=>a.nx-b.nx),x=Math.min(...ordered.map(w=>w.nx)),right=Math.max(...ordered.map(w=>w.nx+w.nw)),y=Math.min(...ordered.map(w=>w.ny)),bottom=Math.max(...ordered.map(w=>w.ny+w.nh));return {text:ordered.map(w=>w.text).join(" "),size:11,bounds:{unit:"norm",x,y,w:right-x,h:bottom-y},fontFamily:"CourierPrime"}})}
const sizes=lines.map(x=>x.size).sort((a,b)=>a-b),median=sizes[Math.floor(sizes.length/2)]||11;lines.forEach((line,i)=>{let type="paragraph";if((line.size>median*1.3||(/^[A-Z0-9 &\-]{4,}$/.test(line.text)&&line.text.length<90)))type="heading";if(i<2&&line.text.length<100)type=type==="heading"?"heading":"header";if(i>=lines.length-2&&line.text.length<100)type="footer";blocks.push({id:"p"+pageNo+"-b"+i,page:pageNo,type,text:line.text,originalText:line.text,bounds:line.bounds,style:{bold:type==="heading",alignment:"left",fontSize:type==="heading"?18:11,fontFamily:matchFontChoice(line.fontFamily)},source:items.length>=3?"pdf-text":"ocr"})})}
return blocks}
function matchFontChoice(name=""){const n=String(name).toLowerCase();if(n.includes("courier")||n.includes("mono"))return "CourierPrime";if(n.includes("times")||n.includes("serif"))return "NotoSerif";if(n.includes("lato"))return "Lato";if(n.includes("symbol")||n.includes("dingbat"))return "NotoSymbols";if(n.includes("helvetica")||n.includes("arial")||n.includes("sans"))return "NotoSans";return "auto"}
function cssFontName(choice){return ({Helvetica:"Arial",TimesRoman:"Times New Roman",Courier:"Courier New",Lato:"Lato",NotoSans:"Arial",NotoSerif:"Georgia",CourierPrime:"Courier New",NotoSymbols:"Arial"})[choice]||"Arial"}
function renderWordDocument(){const doc=$("#wordDocument");doc.innerHTML="";let currentPage=1;documentModel.forEach((b,i)=>{if(b.page!==currentPage){const br=document.createElement("div");br.className="page-break";br.dataset.pageBreak=b.page;doc.append(br);currentPage=b.page}const el=document.createElement(b.type==="heading"?"h2":"div");el.className="doc-block";el.contentEditable="true";el.dataset.id=b.id;el.dataset.type=b.type;el.style.setProperty("--block-font",cssFontName(b.style?.fontFamily));el.textContent=b.text;el.addEventListener("focus",()=>selectBlock(b.id));el.addEventListener("click",()=>selectBlock(b.id));el.addEventListener("input",()=>{b.text=el.innerText;renderStructure()});doc.append(el)});renderStructure();if(documentModel[0])selectBlock(documentModel[0].id)}
function selectBlock(id){activeBlockId=id;document.querySelectorAll(".doc-block,.structure-item").forEach(x=>x.classList.toggle("active",x.dataset.id===id));const b=documentModel.find(x=>x.id===id);if(b){$("#blockStyle").value=b.type;$("#fontFamilySelect").value=b.style?.fontFamily||"auto"}}
function renderStructure(){const list=$("#structureList");list.innerHTML="";documentModel.forEach(b=>{const item=document.createElement("div");item.className="structure-item"+(b.id===activeBlockId?" active":"");item.dataset.id=b.id;item.innerHTML="<b>"+b.type+"</b><span></span>";item.querySelector("span").textContent=b.text||"(empty block)";item.onclick=()=>{selectBlock(b.id);document.querySelector('.doc-block[data-id="'+b.id+'"]')?.scrollIntoView({behavior:"smooth",block:"center"})};list.append(item)});const ocrCount=documentModel.filter(b=>b.source==="ocr").length;$("#conversionWarnings").textContent=ocrCount?ocrCount+" blocks were reconstructed with OCR. Check spelling and line order before export.":"Layout was converted from embedded PDF text. Check tables, columns, and page breaks before export."}
$("#fontFamilySelect").addEventListener("change",e=>{const b=documentModel.find(x=>x.id===activeBlockId);if(!b)return;b.style.fontFamily=e.target.value;const el=document.querySelector('.doc-block[data-id="'+b.id+'"]');if(el)el.style.setProperty("--block-font",cssFontName(e.target.value))});
$("#blockStyle").addEventListener("change",e=>{const b=documentModel.find(x=>x.id===activeBlockId);if(!b)return;b.type=e.target.value;const el=document.querySelector('.doc-block[data-id="'+b.id+'"]');el.dataset.type=b.type;renderStructure()});
document.querySelectorAll("[data-command]").forEach(btn=>btn.addEventListener("click",()=>{document.execCommand(btn.dataset.command,false,null);document.querySelector('.doc-block[data-id="'+activeBlockId+'"]')?.focus()}));
function moveBlock(direction){const i=documentModel.findIndex(x=>x.id===activeBlockId),to=i+direction;if(i<0||to<0||to>=documentModel.length)return;[documentModel[i],documentModel[to]]=[documentModel[to],documentModel[i]];renderWordDocument();selectBlock(activeBlockId)}
$("#moveBlockUp").onclick=()=>moveBlock(-1);$("#moveBlockDown").onclick=()=>moveBlock(1);
$("#addPageBreak").onclick=()=>{const el=document.querySelector('.doc-block[data-id="'+activeBlockId+'"]');if(!el)return;const br=document.createElement("div");br.className="page-break";el.after(br)};
async function renderOriginalReference(){const host=$("#wordOriginalPages");host.innerHTML="";for(let n=1;n<=state.pdf.numPages;n++){const page=await state.pdf.getPage(n),vp=page.getViewport({scale:.72}),canvas=document.createElement("canvas"),displayScale=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(vp.width*displayScale);canvas.height=Math.floor(vp.height*displayScale);canvas.style.width=vp.width+"px";canvas.style.height=vp.height+"px";host.append(canvas);await page.render({canvasContext:canvas.getContext("2d"),viewport:vp,transform:displayScale===1?null:[displayScale,0,0,displayScale,0,0]}).promise}}
$("#exportDocx").onclick=async()=>{if(!window.docx){toast("Word export library did not load");return}const btn=$("#exportDocx");btn.disabled=true;btn.textContent="Preparing Word file…";try{const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType}=window.docx;const children=[];documentModel.forEach((b,i)=>{const el=document.querySelector('.doc-block[data-id="'+b.id+'"]');b.text=el?el.innerText:b.text;const options={children:[new TextRun({text:b.text,bold:b.type==="heading"})],spacing:{after:b.type==="heading"?180:100,line:276}};if(b.type==="heading")options.heading=HeadingLevel.HEADING_1;if(b.type==="header"||b.type==="footer")options.style="Caption";children.push(new Paragraph(options));if(i<documentModel.length-1&&documentModel[i+1].page!==b.page)children.push(new Paragraph({pageBreakBefore:true}))});const file=new Document({sections:[{properties:{},children}]}),blob=await Packer.toBlob(file),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,"")+".docx";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Word document downloaded")}catch(e){console.error(e);toast("Could not create Word document")}finally{btn.disabled=false;btn.textContent="Download Word (.docx)"}};

async function replaceWorkingPdf(bytes,name,message){const file=new File([bytes],name||state.name,{type:"application/pdf"});await loadFile(file);toast(message)}
$("#mergePdfBtn").onclick=()=>$("#mergePdfInput").click();
$("#mergePdfInput").addEventListener("change",async e=>{const files=[...e.target.files];if(!files.length)return;const btn=$("#mergePdfBtn");btn.disabled=true;btn.textContent="Merging…";try{const target=await PDFLib.PDFDocument.load(state.bytes.slice());for(const file of files){const source=await PDFLib.PDFDocument.load(await file.arrayBuffer()),pages=await target.copyPages(source,source.getPageIndices());pages.forEach(p=>target.addPage(p))}const bytes=await target.save();await replaceWorkingPdf(bytes,state.name,files.length+" PDF"+(files.length>1?"s":"")+" merged")}catch(err){console.error(err);toast("Could not merge one of the PDFs")}finally{btn.disabled=false;btn.textContent="⇄ Merge PDF";e.target.value=""}});
$("#addPageBtn").onclick=async()=>{const btn=$("#addPageBtn");btn.disabled=true;try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice()),last=doc.getPage(doc.getPageCount()-1),size=last.getSize();doc.addPage([size.width,size.height]);const bytes=await doc.save();await replaceWorkingPdf(bytes,state.name,"Blank page added")}catch(err){console.error(err);toast("Could not add page")}finally{btn.disabled=false}};
$("#deletePageBtn").onclick=async()=>{try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice());if(doc.getPageCount()<=1){toast("A PDF must keep at least one page");return}const page=Math.min(state.currentPage,doc.getPageCount());doc.removePage(page-1);const bytes=await doc.save();state.currentPage=Math.max(1,page-1);await replaceWorkingPdf(bytes,state.name,"Page "+page+" deleted")}catch(err){console.error(err);toast("Could not delete page")}};
function syncWordModelFromEditor(){documentModel.forEach(b=>{const el=document.querySelector('.doc-block[data-id="'+b.id+'"]');if(el)b.text=el.innerText})}
async function wordToPdfBytes(){if(!window.html2pdf)throw new Error("PDF export library did not load");syncWordModelFromEditor();const source=$("#wordDocument").cloneNode(true);source.querySelectorAll("[contenteditable]").forEach(el=>el.removeAttribute("contenteditable"));source.classList.add("exporting");source.style.boxShadow="none";source.style.margin="0";source.style.width="794px";const holder=document.createElement("div");holder.style.position="fixed";holder.style.left="-10000px";holder.style.top="0";holder.append(source);document.body.append(holder);try{const worker=html2pdf().set({margin:0,html2canvas:{scale:2,useCORS:true,backgroundColor:"#ffffff"},jsPDF:{unit:"pt",format:"a4",orientation:"portrait"},pagebreak:{mode:["css","legacy"],before:".page-break"}}).from(source).toPdf();const pdf=await worker.get("pdf");return pdf.output("arraybuffer")}finally{holder.remove()}}
$("#exportWordPdf").onclick=async()=>{const btn=$("#exportWordPdf");btn.disabled=true;btn.textContent="Preparing PDF…";try{const bytes=await wordToPdfBytes(),blob=new Blob([bytes],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,"")+"-word-edited.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Edited PDF downloaded")}catch(err){console.error(err);toast("Could not create edited PDF")}finally{btn.disabled=false;btn.textContent="Download edited PDF"}};
const fontSources={Lato:"https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/lato/Lato-Regular.ttf",NotoSans:"https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notosans/NotoSans%5Bwdth,wght%5D.ttf",NotoSerif:"https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notoserif/NotoSerif%5Bwdth,wght%5D.ttf",CourierPrime:"https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/courierprime/CourierPrime-Regular.ttf",NotoSymbols:"https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notosanssymbols2/NotoSansSymbols2-Regular.ttf"};
async function embedChosenFont(doc,choice,bold=false,cache=new Map()){const key=choice+"-"+bold;if(cache.has(key))return cache.get(key);let font;if(!choice||choice==="auto"||choice==="Helvetica")font=await doc.embedFont(bold?PDFLib.StandardFonts.HelveticaBold:PDFLib.StandardFonts.Helvetica);else if(choice==="TimesRoman")font=await doc.embedFont(bold?PDFLib.StandardFonts.TimesRomanBold:PDFLib.StandardFonts.TimesRoman);else if(choice==="Courier")font=await doc.embedFont(bold?PDFLib.StandardFonts.CourierBold:PDFLib.StandardFonts.Courier);else{try{if(window.fontkit)doc.registerFontkit(window.fontkit);const bytes=await fetch(fontSources[choice]).then(r=>{if(!r.ok)throw new Error("Font download failed");return r.arrayBuffer()});font=await doc.embedFont(bytes,{subset:true})}catch(e){console.warn("Font fallback",choice,e);font=await doc.embedFont(bold?PDFLib.StandardFonts.HelveticaBold:PDFLib.StandardFonts.Helvetica)}}cache.set(key,font);return font}
async function applyWordChangesPreservingDesign(){syncWordModelFromEditor();const changed=documentModel.filter(b=>b.text!==b.originalText&&b.bounds);if(!changed.length){toast("No text changes to apply");return null}const doc=await PDFLib.PDFDocument.load(state.bytes.slice()),fontCache=new Map();for(const b of changed){const page=doc.getPage(b.page-1),size=page.getSize();let x,y,w,h;if(b.bounds.unit==="norm"){x=b.bounds.x*size.width;w=b.bounds.w*size.width;h=Math.max(8,b.bounds.h*size.height);y=size.height-(b.bounds.y+b.bounds.h)*size.height}else{x=b.bounds.x;y=b.bounds.y;w=b.bounds.w;h=b.bounds.h}const font=await embedChosenFont(doc,b.style?.fontFamily,b.type==="heading"||b.style?.bold,fontCache);let fontSize=Math.max(5,Math.min(b.style?.fontSize||11,h*.82));while(font.widthOfTextAtSize(b.text,fontSize)>w&&fontSize>5)fontSize-=.35;page.drawRectangle({x:x-1.5,y:y-1.5,width:w+3,height:h+3,color:PDFLib.rgb(1,1,1)});page.drawText(b.text,{x,y:y+Math.max(1,(h-fontSize)*.35),size:fontSize,font,color:PDFLib.rgb(.05,.06,.08),maxWidth:w})}return doc.save()}
$("#applyWordToPdf").onclick=async()=>{const btn=$("#applyWordToPdf");btn.disabled=true;btn.textContent="Applying edits…";try{const bytes=await applyWordChangesPreservingDesign();if(!bytes)return;$("#wordEditor").hidden=true;els.editor.hidden=false;await replaceWorkingPdf(bytes,state.name.replace(/\.pdf$/i,"")+"-edited.pdf","Text edits applied — original design preserved");els.wordBtn.textContent="Word Mode"}catch(err){console.error(err);toast("Could not apply Word edits")}finally{btn.disabled=false;btn.textContent="Apply edits back to PDF"}};
function selectedPageNumbers(){const pages=[...state.selectedPages].filter(n=>n>=1&&n<=state.pdf.numPages).sort((a,b)=>a-b);return pages.length?pages:[state.currentPage]}
async function rebuildPdfWithOrder(order,message){const source=await PDFLib.PDFDocument.load(state.bytes.slice()),target=await PDFLib.PDFDocument.create(),copies=await target.copyPages(source,order.map(n=>n-1));copies.forEach(p=>target.addPage(p));await replaceWorkingPdf(await target.save(),state.name,message)}
async function reorderPdfPage(from,to){try{const order=Array.from({length:state.pdf.numPages},(_,i)=>i+1),moved=order.splice(from-1,1)[0];order.splice(to-1,0,moved);await rebuildPdfWithOrder(order,"Page "+from+" moved to position "+to)}catch(err){console.error(err);toast("Could not reorder pages")}}
async function rotateSelected(delta){const pages=selectedPageNumbers();try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice());pages.forEach(n=>{const page=doc.getPage(n-1),angle=((page.getRotation().angle||0)+delta+360)%360;page.setRotation(PDFLib.degrees(angle))});await replaceWorkingPdf(await doc.save(),state.name,pages.length+" page"+(pages.length>1?"s":"")+" rotated")}catch(err){console.error(err);toast("Could not rotate selected pages")}}
$("#rotateLeftBtn").onclick=()=>rotateSelected(-90);$("#rotateRightBtn").onclick=()=>rotateSelected(90);
$("#duplicatePageBtn").onclick=async()=>{const selected=new Set(selectedPageNumbers()),order=[];for(let n=1;n<=state.pdf.numPages;n++){order.push(n);if(selected.has(n))order.push(n)}try{await rebuildPdfWithOrder(order,selected.size+" page"+(selected.size>1?"s":"")+" duplicated")}catch(err){console.error(err);toast("Could not duplicate pages")}};
$("#extractPageBtn").onclick=async()=>{const pages=selectedPageNumbers();try{const source=await PDFLib.PDFDocument.load(state.bytes.slice()),target=await PDFLib.PDFDocument.create(),copies=await target.copyPages(source,pages.map(n=>n-1));copies.forEach(p=>target.addPage(p));const bytes=await target.save(),blob=new Blob([bytes],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,"")+"-pages-"+pages.join("-")+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(pages.length+" page"+(pages.length>1?"s":"")+" extracted")}catch(err){console.error(err);toast("Could not extract pages")}};
$("#deletePageBtn").onclick=async()=>{const pages=selectedPageNumbers();try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice());if(pages.length>=doc.getPageCount()){toast("A PDF must keep at least one page");return}pages.slice().sort((a,b)=>b-a).forEach(n=>doc.removePage(n-1));await replaceWorkingPdf(await doc.save(),state.name,pages.length+" page"+(pages.length>1?"s":"")+" deleted")}catch(err){console.error(err);toast("Could not delete selected pages")}};

let enhancedTextView=false;
$("#enhanceTextBtn").onclick=()=>{enhancedTextView=!enhancedTextView;els.pages.classList.toggle("ocr-enhance",enhancedTextView);$("#enhanceTextBtn").classList.toggle("active",enhancedTextView);$("#enhanceTextBtn").textContent=enhancedTextView?"Show original scan":"Enhance scan text";$("#statusText").textContent=enhancedTextView?"Enhanced OCR text view — original PDF remains unchanged":"Original scan view"};
